services:
  create-user:
    build: ./create-user-service
    volumes:
      - ./create-user-service:/app
    ports:
      - "3001:3001"
    networks:
      - internal-network

  edit-user:
    build: ./edit-user-service
    volumes:
      - ./edit-user-service:/app
    ports:
      - "3002:3002"
    networks:
      - internal-network

  delete-user:
    build: ./delete-user-service
    volumes:
      - ./delete-user-service:/app
    ports:
      - "3003:3003"
    networks:
      - internal-network

  read-user:
    build: ./read-user-service
    volumes:
      - ./read-user-service:/app
    ports:
      - "3004:3004"
    networks:
      - internal-network

  loger-user:
    build: ./loger-user-service
    volumes:
      - ./loger-user-service:/app
    ports:
      - "3005:3005"
    networks:
      - internal-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - internal-network

networks:
  internal-network:

volumes:
  mongo-data:
